name: Code Quality
on:
  pull_request:
    branches: [develop]
    types: [opened, reopened, synchronize]
  workflow_dispatch:
jobs:
  test:
    name: Lint and test
    # Linting and Testing should never take longer than 10 minutes
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Get target branch
        run: |
          branch=${{ github.event.pull_request.base.ref }}
          echo "branch=${branch}" >> $GITHUB_OUTPUT

          echo "::group::Branch"
          echo 'branch: '${branch}
          echo "::endgroup::"
        shell: bash
        id: target_branch

      - name: Get environment
        run: |
          env=dev
          if [[ "${{ steps.target_branch.outputs.branch }}" == "main" ]]; then
            env=prod
          fi
          echo "env_name=${env}" >> $GITHUB_OUTPUT

          echo "::group::Environment"
          echo 'environment: '${env}
          echo "::endgroup::"
        shell: bash
        id: environment

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed theme files
        id: changed-theme
        uses: tj-actions/changed-files@v39
        with:
          files: |
            themes/**
            .github/workflows/test.yml

      - name: Get changed markdown files
        id: changed-markdown
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **/*.md
            .github/workflows/test.yml

      - name: Lint all Documentation
        if: steps.changed-markdown.outputs.any_modified == 'true'
        uses: DavidAnson/markdownlint-cli2-action@v14
        with:
          globs: |
            **/*.md
            !**/plugins/**

      - name: Lint
        if: steps.changed-theme.outputs.any_modified == 'true'
        uses: 10up/wpcs-action@stable
        with:
          paths: './themes' # Paths to check, space separated
          standard: 'WordPress' # Standard to use. Accepts WordPress|WordPress-Core|WordPress-Docs|WordPress-Extra|WordPress-VIP-Go|WordPressVIPMinimum|10up-Default.
          extra_args: '--report-json=./phpcs.json'

      - name: Update summary
        run: |
          npm i -g github:10up/phpcs-json-to-md
          phpcs-json-to-md --path ./phpcs.json --output ./phpcs.md
          cat phpcs.md >> $GITHUB_STEP_SUMMARY
        shell: bash
        if: always()
